version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.20
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-42
        port: 4466
        databases:
          default:
            connector: mysql
            host: 172.17.0.1
            port: 3306
            user: prisma
            password: prisma
            migrations: true
            ssl: false
